# Development stage
# Use a Node.js base image for development
FROM node:14 as builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install development dependencies
RUN npm install

# Copy the source code to the container
COPY . .

# Start the development server
CMD ["npm", "start"]

# Build the application 
RUN npm run build


# Production stage
# Use a smaller Node.js base image for production
FROM nginx:alpine 

# Copy the built application from the 'builder' stage
COPY --from=builder /app/build /usr/share/nginx/html

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install only production dependencies
RUN npm install --only=production

# Copy the built application from the development stage
COPY --from=development /app .

# Expose the application port
EXPOSE 3000

# Start the production server
CMD ["npm", "start"]
